#!/bin/sh
touch /etc/crontabs/root

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci set system.@system[0].hostname=iWRT
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci -q del system.ntp.server
uci -q add_list system.ntp.server='ntp.aliyun.com'
uci -q add_list system.ntp.server='time1.cloud.tencent.com'
uci -q add_list system.ntp.server='time.ustc.edu.cn'
uci -q add_list system.ntp.server='cn.pool.ntp.org'
uci -q add_list system.ntp.server='0.openwrt.pool.ntp.org'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set mosdns.mosdns.enabled='1'
uci set mosdns.mosdns.adblock='1'
uci set mosdns.mosdns.not_first_start='1'
uci set mosdns.mosdns.geo_auto_update='1'
uci commit mosdns


uci set smartdns.smartdns.enabled='1'
uci commit smartdns


uci set uhttpd.main.redirect_https='0'
uci commit uhttpd

ln -sf /sbin/ip /usr/bin/ip

uci set network.lan.ipaddr="192.168.8.1"
uci set network.lan.netmask='255.255.255.0'
#uci set network.lan.dns='127.0.0.1'
uci set network.lan.ifname="eth0"
uci set network.wan.ifname="eth1"
uci commit network

uci set upnpd.config.enabled='1'
uci set upnpd.config.external_iface="wan"
uci commit upnpd

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm


sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/cupsd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/nfs.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/cifs.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/qbittorrent.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
sed -i 's/\"network\"/\"services\"/g' /usr/lib/lua/luci/controller/dnspod.lua
sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/qosv4.lua
sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/eqos.lua
sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/qos_gargoyle.lua
#sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/qos.lua
sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/sqm.lua
sed -i 's/\"services\"/\"QOS\"/g' /usr/lib/lua/luci/controller/nft-qos.lua
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/softethervpn5.lua
sed -i 's/\"network\"/\"control\"/g' /usr/lib/lua/luci/controller/appfilter.lua
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/wol.lua


#sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
sed -i 's/downloads.openwrt.org/mirrors.cloud.tencent.com\/openwrt/g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf

uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci set dhcp.dnsmasq.filter_aaaa='1' #关闭解析ipv6
uci -q add_list dnsmasq.server='127.0.0.1#54'
uci commit dhcp

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo '#允许本机的53端口可对外访问' >> /etc/firewall.user
echo '#iptables -A INPUT -p udp -m udp --dport 53 -j ACCEPT' >> /etc/firewall.user
echo '#iptables -A INPUT -p tcp -m tcp --dport 53 -j ACCEPT' >> /etc/firewall.user

# 开启流量转发功能
#echo '1' >> /proc/sys/net/ipv4/ip_forward
#echo '1' >> /proc/sys/net/ipv6/ip_forward

echo '#流量转发规则，将外部到53的端口的请求映射到Dnsmasq服务器的53端口' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user


sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='@20.6.29 From Lienol'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OneWrt '" >> /etc/openwrt_release

sed -i '/DISTRIB_ID/d' /etc/openwrt_release
echo "DISTRIB_ID='iWRT'" >> /etc/openwrt_release

# NEVER DROP THE EXISTING AUTHORS INFO | 禁止删除现有作者信息
#sed -i 's/LuCI 17.01 Lienol/LuCI 17.01/g' /usr/lib/lua/luci/version.lua

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/kcptun disable 2>/dev/null

chmod 0755 /etc/init.d/*
chmod 0755 /etc/init.d/netdata

rm -rf /tmp/luci-*cache

#禁用ipv6.
#echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
#echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
#echo net.ipv6.conf.lo.disable_ipv6 = 1 >> /etc/sysctl.conf
#echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6

exit 0
